--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOBAYBOARD"."NUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "HOBAYBOARD"."BOARD" 
   (	"NUM" NUMBER DEFAULT NULL, 
	"USERNAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(30 BYTE), 
	"MEMO" VARCHAR2(200 BYTE), 
	"TIME" DATE DEFAULT sysdate, 
	"REF" NUMBER DEFAULT 0, 
	"INDENT" NUMBER DEFAULT 0, 
	"STEP" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HOBAYBOARD.BOARD
SET DEFINE OFF;
Insert into HOBAYBOARD.BOARD (NUM,USERNAME,PASSWORD,TITLE,MEMO,TIME,REF,INDENT,STEP) values (1,'오정우','1234','안녕하세요','오정우',to_date('21/06/18','RR/MM/DD'),0,0,0);
--------------------------------------------------------
--  DDL for Index SYS_C007670
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOBAYBOARD"."SYS_C007670" ON "HOBAYBOARD"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007670
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOBAYBOARD"."SYS_C007670" ON "HOBAYBOARD"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "HOBAYBOARD"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
